site_name: Kobold Archives
site_author: Jacques du Plessis
copyright: No Commercial Licence - All rights reserved Jacques du Plessis
site_url: https://jacques-dup.github.io/karchives/
repo_name: 'jacques-dup/karchives'
repo_url: 'https://github.com/jacques-dup/karchives'
theme:
  name: material
extra_css:
  - ./assets/css/custom.css
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/jacques-dup/karchives
        - icon: fontawesome/regular/envelope-open
          link: mailto:jdples@gmail.com
theme:
    name: material
    icon:
        logo: material/library
    favicon: ./assets/favicon.png
    language: en
    palette:
        primary: deep-purple
        accent: amber
    font:
        text: Ubuntu
        code: Ubuntu Mono
    features:
        # tabs
markdown_extensions:
    - toc:
          permalink: false
    - pymdownx.caret
    - pymdownx.tilde
    # for suprescripts, us ^ and subscripts with ~
    - pymdownx.magiclink
    - pymdownx.smartsymbols
    - pymdownx.details
    # for dropout/accordion elements
      # ??? optional-class "Summary"
      # Here's some content.
    - pymdownx.escapeall
    # enable escaping with \
    - pymdownx.extra
    # BetterEm pymdownx.betterem
    # SuperFences	pymdownx.superfences
    # Footnotes	markdown.extensions.footnotes
    # Attribute Lists	markdown.extensions.attr_list
    # Definition Lists	markdown.extensions.def_list
    # Tables	markdown.extensions.tables
    # Abbreviations	markdown.extensions.abbr
    # ExtraRawHTML	pymdownx.extrarawhtml
    - pymdownx.mark:
        smart_mark: true
    # for highlights with == ==
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - markdown_blockdiag:
          format: svg
    # Use this for timeline and event maps
    - markdown_include.include
    - admonition
nav:
  - index.md
  - Dev Diary:
    - about/readme_page.md
  - Geography:
    - geography/aklatoria.md
    - geography/realms/agaea.md
    - geography/realms/caenar.md
    - geography/realms/casavano.md
    - geography/realms/halherant.md
    - geography/realms/iantear.md
    - geography/realms/ilior.md
    - geography/realms/kalbaek.md
    - geography/realms/kalibora.md
    - geography/realms/kethraelm.md
    - geography/realms/ksher.md
    - geography/realms/menassim.md
    - geography/realms/meshatl.md
    - geography/realms/niarnfell.md
    - geography/realms/saesamen.md
  - Cosmology:
    - cosmology/index.md
    - cosmology/magic.md
    - cosmology/planes.md
    - Places of Power:
      - cosmology/magic/places_of_power/world_trees.md
    - List of Planes:
      - cosmology/planes/aegis.md
      - cosmology/planes/artificium_campestribus.md
      - cosmology/planes/crevatorus.md
      - cosmology/planes/eltis.md
      - cosmology/planes/elysium.md
      - cosmology/planes/eskall.md
      - cosmology/planes/gaia.md
      - cosmology/planes/heldar.md
      - cosmology/planes/kelon.md
      - cosmology/planes/kesra.md
      - cosmology/planes/materia.md
      - cosmology/planes/myst.md
      - cosmology/planes/nox.md
      - cosmology/planes/onus.md
      - cosmology/planes/ordinia.md
      - cosmology/planes/reilagg.md
      - cosmology/planes/ruune.md
      - cosmology/planes/shole.md
      - cosmology/planes/tartarus.md
      - cosmology/planes/tundrum_arctis.md
      - cosmology/planes/umber.md
      - cosmology/planes/void_of_creation.md
  - Races:
    - people/races/aarakocra.md
    - people/races/chentoo.md
    - people/races/dragonborn.md
    - people/races/dwarves.md
    - people/races/elves.md
    - people/races/gnomes.md
    - people/races/half_elves.md
    - people/races/half_orcs.md
    - people/races/halflings.md
    - people/races/humans.md
    - people/races/kobolds.md
    - people/races/tieflings.md
  - Language:
    - language/dwarven.md
    - language/vestii.md
  - Religion:
    - religion/index.md
    - Religious Organizations:
      - religion/organizations/benign_assembly.md
      - religion/organizations/chantry_of_the_sisters.md
      - religion/organizations/church_of_blood_and_bone.md
      - religion/organizations/church_of_night.md
      - religion/organizations/circle_of_arcana.md
      - religion/organizations/circle_of_justice.md
      - religion/organizations/circle_of_vitalis.md
      - religion/organizations/court_of_the_white_mask.md
      - religion/organizations/cult_of_the_black_cloud.md
      - religion/organizations/divine_arcanum.md
      - religion/organizations/dwarf_ancestry.md
      - religion/organizations/elemental_courts.md
      - religion/organizations/friars_of_the_tankard.md
      - religion/organizations/herds_of_the_shepherd.md
      - religion/organizations/house_of_dawn.md
      - religion/organizations/orc_ancestry.md
      - religion/organizations/order_of_paragon.md
      - religion/organizations/order_of_sentinel.md
      - religion/organizations/order_of_the_third_eye.md
      - religion/organizations/ordos_valorium.md
      - religion/organizations/path_of_the_secret_scrolls.md
      - religion/organizations/sanguine.md
      - religion/organizations/unyielding.md
      - religion/organizations/way_of_the_primordial_serpent.md
      - religion/organizations/winter_touched.md
    - List of Deities:
      - religion/deities/armara.md
      - religion/deities/assador.md
      - religion/deities/callad.md
      - religion/deities/duswyn.md
      - religion/deities/dwarf_old_ones.md
      - religion/deities/elmara.md
      - religion/deities/erigrim.md
      - religion/deities/erthan.md
      - religion/deities/firna.md
      - religion/deities/garkash.md
      - religion/deities/heron.md
      - religion/deities/hhoru.md
      - religion/deities/irthor_&_kidan.md
      - religion/deities/kaerlun.md
      - religion/deities/lafarn.md
      - religion/deities/lenkinfail.md
      - religion/deities/leonne.md
      - religion/deities/lex_fireheart.md
      - religion/deities/lilith.md
      - religion/deities/lord_aster.md
      - religion/deities/madis.md
      - religion/deities/maia.md
      - religion/deities/manos_claye.md
      - religion/deities/martivir.md
      - religion/deities/naash_feramil.md
      - religion/deities/nahua.md
      - religion/deities/nimwind.md
      - religion/deities/nod.md
      - religion/deities/odian.md
      - religion/deities/opus.md
      - religion/deities/ornim.md
      - religion/deities/rumara_caelan.md
      - religion/deities/seth.md
      - religion/deities/shaeleon.md
      - religion/deities/stryder.md
      - religion/deities/throden.md
      - religion/deities/tooloo.md
      - religion/deities/tor.md
      - religion/deities/ura.md
      - religion/deities/vonryl_kethalon.md
      - religion/deities/zarach.md
  - Mythical History:
    - Myths:
      - history/myths/seeds_of_life.md
      - history/myths/black_seeding.md
      - history/myths/creation_dwarves.md
      - Artifacts:
        - cosmology/magic/mythical_artifacts/rune_stone.md
        - cosmology/magic/mythical_artifacts/scrolls_of_creation.md
        - cosmology/magic/mythical_artifacts/thirteen_seals_of_being.md
    - Primary Sources:
      - history/artifacts/book_of_arath_aev.md
      - history/artifacts/six_tablets_of_verashuun.md
    - history/ages/before_history.md
    - history/ages/age_of_seeding.md
    - history/ages/time_of_turmoil.md
    - history/ages/age_of_stone.md
    - history/ages/age_of_the_stars.md
    - history/ages/long_winter.md
    - history/ages/age_of_the_sun.md